Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 20
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - hsd_circle_reports.gemspec

Metrics/PerceivedComplexity:
  Max: 15
